name: GitHub Pages

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  vite:
    uses: area44/actions/.github/workflows/vite.yml@v0.4.1
    with:
      run_deploy: true
