name: Deploy Vite Site

on:
  push:
    branches: ['main']
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: area44/workflow-hub/.github/workflows/vite.yml@v0.3.1
    with:
      run_deploy: true
